server:
  port: 8080

spring:
  application:
    name: euler-cloud-image
  datasource:
    url: jdbc:mysql://localhost:3306/euler_cloud_image?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

euler:
  runtime-path: /var/lib/euler-cloud/image
  image:
    thumbMaxSize: 400
    thumbQuality: 0.618